/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiPenthousesRouteImport } from './routes/api/penthouses'
import { Route as ApiContactMessagesRouteImport } from './routes/api/contact-messages'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiBookingsRouteImport } from './routes/api/bookings'
import { Route as ApiActivitiesRouteImport } from './routes/api/activities'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPenthousesRouteImport } from './routes/admin.penthouses'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPenthousesRoute = ApiPenthousesRouteImport.update({
  id: '/api/penthouses',
  path: '/api/penthouses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactMessagesRoute = ApiContactMessagesRouteImport.update({
  id: '/api/contact-messages',
  path: '/api/contact-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivitiesRoute = ApiActivitiesRouteImport.update({
  id: '/api/activities',
  path: '/api/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenthousesRoute = AdminPenthousesRouteImport.update({
  id: '/penthouses',
  path: '/penthouses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/penthouses': typeof AdminPenthousesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/activities': typeof ApiActivitiesRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/penthouses': typeof ApiPenthousesRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/users': typeof ApiUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/penthouses': typeof AdminPenthousesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/activities': typeof ApiActivitiesRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/penthouses': typeof ApiPenthousesRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/users': typeof ApiUsersRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/penthouses': typeof AdminPenthousesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/activities': typeof ApiActivitiesRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/penthouses': typeof ApiPenthousesRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/users': typeof ApiUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/login'
    | '/admin/penthouses'
    | '/admin/settings'
    | '/admin/users'
    | '/api/activities'
    | '/api/bookings'
    | '/api/contact'
    | '/api/contact-messages'
    | '/api/penthouses'
    | '/api/settings'
    | '/api/upload'
    | '/api/users'
    | '/admin/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/login'
    | '/admin/penthouses'
    | '/admin/settings'
    | '/admin/users'
    | '/api/activities'
    | '/api/bookings'
    | '/api/contact'
    | '/api/contact-messages'
    | '/api/penthouses'
    | '/api/settings'
    | '/api/upload'
    | '/api/users'
    | '/admin'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/login'
    | '/admin/penthouses'
    | '/admin/settings'
    | '/admin/users'
    | '/api/activities'
    | '/api/bookings'
    | '/api/contact'
    | '/api/contact-messages'
    | '/api/penthouses'
    | '/api/settings'
    | '/api/upload'
    | '/api/users'
    | '/admin/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiActivitiesRoute: typeof ApiActivitiesRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiContactMessagesRoute: typeof ApiContactMessagesRoute
  ApiPenthousesRoute: typeof ApiPenthousesRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/penthouses': {
      id: '/api/penthouses'
      path: '/api/penthouses'
      fullPath: '/api/penthouses'
      preLoaderRoute: typeof ApiPenthousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact-messages': {
      id: '/api/contact-messages'
      path: '/api/contact-messages'
      fullPath: '/api/contact-messages'
      preLoaderRoute: typeof ApiContactMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activities': {
      id: '/api/activities'
      path: '/api/activities'
      fullPath: '/api/activities'
      preLoaderRoute: typeof ApiActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/penthouses': {
      id: '/admin/penthouses'
      path: '/penthouses'
      fullPath: '/admin/penthouses'
      preLoaderRoute: typeof AdminPenthousesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPenthousesRoute: typeof AdminPenthousesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPenthousesRoute: AdminPenthousesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiActivitiesRoute: ApiActivitiesRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiContactMessagesRoute: ApiContactMessagesRoute,
  ApiPenthousesRoute: ApiPenthousesRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
