/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApartmentsRouteImport } from './routes/apartments'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiRoomsRouteImport } from './routes/api/rooms'
import { Route as ApiPenthousesRouteImport } from './routes/api/penthouses'
import { Route as ApiGalleryImagesRouteImport } from './routes/api/gallery-images'
import { Route as ApiContactMessagesRouteImport } from './routes/api/contact-messages'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiBookingsRouteImport } from './routes/api/bookings'
import { Route as ApiBookingWhatsappRouteImport } from './routes/api/booking-whatsapp'
import { Route as ApiBookingInquiriesRouteImport } from './routes/api/booking-inquiries'
import { Route as ApiActivitiesRouteImport } from './routes/api/activities'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsRoute = ApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoute = ApiRoomsRouteImport.update({
  id: '/api/rooms',
  path: '/api/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPenthousesRoute = ApiPenthousesRouteImport.update({
  id: '/api/penthouses',
  path: '/api/penthouses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryImagesRoute = ApiGalleryImagesRouteImport.update({
  id: '/api/gallery-images',
  path: '/api/gallery-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactMessagesRoute = ApiContactMessagesRouteImport.update({
  id: '/api/contact-messages',
  path: '/api/contact-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingWhatsappRoute = ApiBookingWhatsappRouteImport.update({
  id: '/api/booking-whatsapp',
  path: '/api/booking-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingInquiriesRoute = ApiBookingInquiriesRouteImport.update({
  id: '/api/booking-inquiries',
  path: '/api/booking-inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivitiesRoute = ApiActivitiesRouteImport.update({
  id: '/api/activities',
  path: '/api/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/amenities': typeof AmenitiesRoute
  '/apartments': typeof ApartmentsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/rooms': typeof RoomsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/activities': typeof ApiActivitiesRoute
  '/api/booking-inquiries': typeof ApiBookingInquiriesRoute
  '/api/booking-whatsapp': typeof ApiBookingWhatsappRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/gallery-images': typeof ApiGalleryImagesRoute
  '/api/penthouses': typeof ApiPenthousesRoute
  '/api/rooms': typeof ApiRoomsRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/users': typeof ApiUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/apartments': typeof ApartmentsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/rooms': typeof RoomsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/activities': typeof ApiActivitiesRoute
  '/api/booking-inquiries': typeof ApiBookingInquiriesRoute
  '/api/booking-whatsapp': typeof ApiBookingWhatsappRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/gallery-images': typeof ApiGalleryImagesRoute
  '/api/penthouses': typeof ApiPenthousesRoute
  '/api/rooms': typeof ApiRoomsRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/users': typeof ApiUsersRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/amenities': typeof AmenitiesRoute
  '/apartments': typeof ApartmentsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/rooms': typeof RoomsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/activities': typeof ApiActivitiesRoute
  '/api/booking-inquiries': typeof ApiBookingInquiriesRoute
  '/api/booking-whatsapp': typeof ApiBookingWhatsappRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/gallery-images': typeof ApiGalleryImagesRoute
  '/api/penthouses': typeof ApiPenthousesRoute
  '/api/rooms': typeof ApiRoomsRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/users': typeof ApiUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/amenities'
    | '/apartments'
    | '/contact'
    | '/gallery'
    | '/rooms'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/gallery'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/api/activities'
    | '/api/booking-inquiries'
    | '/api/booking-whatsapp'
    | '/api/bookings'
    | '/api/contact'
    | '/api/contact-messages'
    | '/api/gallery-images'
    | '/api/penthouses'
    | '/api/rooms'
    | '/api/settings'
    | '/api/upload'
    | '/api/users'
    | '/admin/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/apartments'
    | '/contact'
    | '/gallery'
    | '/rooms'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/gallery'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/api/activities'
    | '/api/booking-inquiries'
    | '/api/booking-whatsapp'
    | '/api/bookings'
    | '/api/contact'
    | '/api/contact-messages'
    | '/api/gallery-images'
    | '/api/penthouses'
    | '/api/rooms'
    | '/api/settings'
    | '/api/upload'
    | '/api/users'
    | '/admin'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/amenities'
    | '/apartments'
    | '/contact'
    | '/gallery'
    | '/rooms'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/gallery'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/api/activities'
    | '/api/booking-inquiries'
    | '/api/booking-whatsapp'
    | '/api/bookings'
    | '/api/contact'
    | '/api/contact-messages'
    | '/api/gallery-images'
    | '/api/penthouses'
    | '/api/rooms'
    | '/api/settings'
    | '/api/upload'
    | '/api/users'
    | '/admin/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AmenitiesRoute: typeof AmenitiesRoute
  ApartmentsRoute: typeof ApartmentsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  RoomsRoute: typeof RoomsRoute
  ApiActivitiesRoute: typeof ApiActivitiesRoute
  ApiBookingInquiriesRoute: typeof ApiBookingInquiriesRoute
  ApiBookingWhatsappRoute: typeof ApiBookingWhatsappRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiContactMessagesRoute: typeof ApiContactMessagesRoute
  ApiGalleryImagesRoute: typeof ApiGalleryImagesRoute
  ApiPenthousesRoute: typeof ApiPenthousesRoute
  ApiRoomsRoute: typeof ApiRoomsRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments': {
      id: '/apartments'
      path: '/apartments'
      fullPath: '/apartments'
      preLoaderRoute: typeof ApartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms': {
      id: '/api/rooms'
      path: '/api/rooms'
      fullPath: '/api/rooms'
      preLoaderRoute: typeof ApiRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/penthouses': {
      id: '/api/penthouses'
      path: '/api/penthouses'
      fullPath: '/api/penthouses'
      preLoaderRoute: typeof ApiPenthousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery-images': {
      id: '/api/gallery-images'
      path: '/api/gallery-images'
      fullPath: '/api/gallery-images'
      preLoaderRoute: typeof ApiGalleryImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact-messages': {
      id: '/api/contact-messages'
      path: '/api/contact-messages'
      fullPath: '/api/contact-messages'
      preLoaderRoute: typeof ApiContactMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-whatsapp': {
      id: '/api/booking-whatsapp'
      path: '/api/booking-whatsapp'
      fullPath: '/api/booking-whatsapp'
      preLoaderRoute: typeof ApiBookingWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-inquiries': {
      id: '/api/booking-inquiries'
      path: '/api/booking-inquiries'
      fullPath: '/api/booking-inquiries'
      preLoaderRoute: typeof ApiBookingInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activities': {
      id: '/api/activities'
      path: '/api/activities'
      fullPath: '/api/activities'
      preLoaderRoute: typeof ApiActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AmenitiesRoute: AmenitiesRoute,
  ApartmentsRoute: ApartmentsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  RoomsRoute: RoomsRoute,
  ApiActivitiesRoute: ApiActivitiesRoute,
  ApiBookingInquiriesRoute: ApiBookingInquiriesRoute,
  ApiBookingWhatsappRoute: ApiBookingWhatsappRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiContactMessagesRoute: ApiContactMessagesRoute,
  ApiGalleryImagesRoute: ApiGalleryImagesRoute,
  ApiPenthousesRoute: ApiPenthousesRoute,
  ApiRoomsRoute: ApiRoomsRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
